### ISSUE TITLE
Error: Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by arichiardi** [noBlubb/uglify-es-webpack-plugin#5]
Hello folks!

I hooked up this plugin in here: https://travis-ci.org/prayerslayer/js.spec/jobs/244723693

Unfortunately it is failing for Node 4 (I know I know).

The error is:

```
/home/travis/build/prayerslayer/js.spec/node_modules/uglify-es-webpack-plugin/src/index.js:12
class UglifyEsPlugin {
^^^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/prayerslayer/js.spec/webpack.config.js:5:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

Do you think it is worth fixing it?

**Comment by noBlubb** [comment]
Hey,

sorry, this started off as an experiment for me and I didn't really care too much about compatibility.
https://github.com/Nckcol/uglify-es-webpack-plugin is an improved fork and offers much more features and seems to references a (transpiled) dist/cjs.js. I will talk to the other maintainers if they are interested to take over the npm package `uglify-es-webpack-plugin` and make sure that there are transpiled releases available :)

**Comment by arichiardi** [comment]
Oh ok I see, thanks! I saw the other one but I could not open issues there 😀
